# PERFIL PROD — Producción

# Thymeleaf con cache para performance
spring.thymeleaf.cache=true

# DevTools deshabilitado en producción
spring.devtools.restart.enabled=false
spring.devtools.livereload.enabled=false

# Seed data deshabilitado
app.seed=false

# Logs solo WARN+ en producción
logging.level.com.residuosolido.app=WARN
logging.level.org.springframework.web=WARN
logging.level.org.springframework.web.servlet.DispatcherServlet=WARN
logging.level.org.springframework.data.mongodb=WARN
logging.level.org.thymeleaf=WARN
